userManager_controllers:
    resource: '../src/userManager/Controller/'
    type: attribute

news_controllers:
    resource: '../src/news/Controller/'
    type: attribute 

todo_controllers:
    resource: '../src/todo/Controller/'
    type: attribute   

cron_controllers:
    resource: '../src/cron/Controller/'
    type: attribute  

api_controllers:
    resource: '../src/api/Controller/'
    type: attribute 
    
api_login_check:
    path: /api/login_check                
        
access_denied:
    path: /access-denied
    controller: App\userManager\Controller\DefaultController::accessDenied