userManager_controllers:
    resource: '../src/userManager/Controller/'
    type: attribute

news_controllers:
    resource: '../src/news/Controller/'
    type: attribute 

todo_controllers:
    resource: '../src/todo/Controller/'
    type: attribute       
        

access_denied:
    path: /access-denied
    controller: App\userManager\Controller\DefaultController::accessDenied